using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace Assertive.Generators
{
  /// <summary>
  /// Intercepts Assert.That / DSL.Assert / [AssertionWrapper] call sites whose lambda body
  /// is a binary ==/!= comparison, replacing delegate evaluation with directly emitted,
  /// typed C#: captured locals are read from the delegate's closure, each operand is
  /// evaluated exactly once, and failures are reported through
  /// GeneratedAssert.EqualityFailure with captured values (EqualsPattern parity).
  ///
  /// There is no expression-tree fallback: call sites outside the whitelist run the plain
  /// delegate and report from source text only, until their patterns are ported.
  /// </summary>
  [Generator]
  public sealed class EqualsInterceptorGenerator : IIncrementalGenerator
  {
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
      var calls = context.SyntaxProvider.CreateSyntaxProvider(
          // Cheap syntax pre-filter: any invocation whose first argument is a zero-parameter
          // lambda literal. The transform's symbol checks reject everything else.
          predicate: static (node, _) => node is InvocationExpressionSyntax invocation
            && invocation.ArgumentList.Arguments.Count > 0
            && invocation.ArgumentList.Arguments[0].Expression is ParenthesizedLambdaExpressionSyntax { ParameterList.Parameters.Count: 0 },
          transform: static (ctx, ct) => CallSiteAnalyzer.Analyze(ctx, ct))
        .Where(static c => c is not null);

      context.RegisterSourceOutput(calls.Collect(), static (spc, all) => Emit(spc, all!));
    }

    private static void Emit(SourceProductionContext spc, ImmutableArray<InterceptedCall?> calls)
    {
      foreach (var fileGroup in calls.Where(c => c != null).GroupBy(c => c!.FilePath))
      {
        // Readable, collision-free: source file stem + stable hash of the full path.
        var stem = new string(System.IO.Path.GetFileNameWithoutExtension(fileGroup.Key)
          .Where(char.IsLetterOrDigit).ToArray());
        var classSuffix = $"{stem}_{StableHash(fileGroup.Key)}";
        var sb = new StringBuilder();

        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable disable");
        sb.AppendLine("#pragma warning disable");
        sb.AppendLine();
        sb.AppendLine("namespace System.Runtime.CompilerServices");
        sb.AppendLine("{");
        sb.AppendLine("  [global::System.AttributeUsage(global::System.AttributeTargets.Method, AllowMultiple = true)]");
        sb.AppendLine("  file sealed class InterceptsLocationAttribute : global::System.Attribute");
        sb.AppendLine("  {");
        sb.AppendLine("    public InterceptsLocationAttribute(int version, string data)");
        sb.AppendLine("    {");
        sb.AppendLine("      _ = version;");
        sb.AppendLine("      _ = data;");
        sb.AppendLine("    }");
        sb.AppendLine("  }");
        sb.AppendLine("}");
        sb.AppendLine();
        sb.AppendLine("namespace Assertive.Generated");
        sb.AppendLine("{");
        sb.AppendLine($"  internal static class AssertThatInterceptors_{classSuffix}");
        sb.AppendLine("  {");

        var index = 0;

        foreach (var call in fileGroup)
        {
          if (call!.Wrapper != null)
          {
            EmitWrapperInterceptor(sb, call, index++);
          }
          else if (call.Kind == InterceptionKind.ThrowsPredicate)
          {
            EmitThrowsInterceptor(sb, call, index++);
          }
          else
          {
            EmitThatInterceptor(sb, call, index++);
          }

          sb.AppendLine();
        }

        sb.AppendLine("  }");
        sb.AppendLine("}");

        spc.AddSource($"AssertThatInterceptors_{classSuffix}.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
      }
    }

    private static void EmitThatInterceptor(StringBuilder sb, InterceptedCall call, int index)
    {
      var parameters = call.Overload switch
      {
        ThatOverload.Context => "global::System.Func<bool> __assertion, global::System.Func<object> __context, string __expr, string __contextExpr",
        _ => "global::System.Func<bool> __assertion, object __message, global::System.Func<object> __context, string __expr, string __contextExpr",
      };

      var messageArg = call.Overload is ThatOverload.MessageContext ? "__message" : "null";
      var contextArg = "__context";
      var contextExprArg = "__contextExpr";

      sb.AppendLine($"    // {call.DisplayLocation}");
      sb.AppendLine("    [global::System.Diagnostics.StackTraceHidden]");
      sb.AppendLine($"    [global::System.Runtime.CompilerServices.InterceptsLocation({call.LocationVersion}, {Quote(call.LocationData)})]");
      sb.AppendLine($"    public static void That{index}({parameters})");
      sb.AppendLine("    {");
      sb.AppendLine("      try");
      sb.AppendLine("      {");
      EmitEvaluation(sb, call, "__assertion", "__expr", $"{messageArg}, {contextArg}, {contextExprArg}", "        ");
      sb.AppendLine("      }");
      sb.AppendLine("      catch (global::System.Exception __ex) when (!global::Assertive.Runtime.GeneratedAssert.IsAssertionFailure(__ex))");
      sb.AppendLine("      {");
      EmitExceptionHandler(sb, call, "__assertion", "__expr", $"{messageArg}, {contextArg}, {contextExprArg}", "        ");
      sb.AppendLine("      }");
      sb.AppendLine("    }");
    }

    /// <summary>
    /// Emits an interceptor for an [AssertionWrapper] call site: routes to the wrapper's
    /// AssertionHandle overload carrying a generated assertion action. Instance wrappers
    /// are intercepted with an extension method (receiver as first parameter).
    /// </summary>
    private static void EmitWrapperInterceptor(StringBuilder sb, InterceptedCall call, int index)
    {
      var wrapper = call.Wrapper!;

      var parameters = new List<string>();

      if (!wrapper.IsStatic)
      {
        parameters.Add($"this {wrapper.ContainingTypeFqn} __receiver");
      }

      parameters.Add("global::System.Func<bool> __assertion");

      for (var i = 0; i < wrapper.ExtraParameterTypes.Count; i++)
      {
        parameters.Add($"{wrapper.ExtraParameterTypes[i]} __p{i}");
      }

      var forwardedArgs = string.Concat(Enumerable.Range(0, wrapper.ExtraParameterTypes.Count).Select(i => $", __p{i}"));
      var target = wrapper.IsStatic ? wrapper.ContainingTypeFqn : "__receiver";
      var returnKeyword = wrapper.ReturnTypeFqn == "void" ? "" : "return ";
      var bodyText = Quote(call.BodySource);

      sb.AppendLine($"    // {call.DisplayLocation}");
      sb.AppendLine("    [global::System.Diagnostics.StackTraceHidden]");
      sb.AppendLine($"    [global::System.Runtime.CompilerServices.InterceptsLocation({call.LocationVersion}, {Quote(call.LocationData)})]");
      sb.AppendLine($"    public static {wrapper.ReturnTypeFqn} Wrapper{index}({string.Join(", ", parameters)})");
      sb.AppendLine("    {");
      sb.AppendLine($"      {returnKeyword}{target}.{wrapper.MethodName}(global::Assertive.AssertionHandle.Generated([global::System.Diagnostics.StackTraceHidden] () =>");
      sb.AppendLine("      {");
      sb.AppendLine("        try");
      sb.AppendLine("        {");
      EmitEvaluation(sb, call, "__assertion", bodyText, "null, null, null", "          ");
      sb.AppendLine("        }");
      sb.AppendLine("        catch (global::System.Exception __ex) when (!global::Assertive.Runtime.GeneratedAssert.IsAssertionFailure(__ex))");
      sb.AppendLine("        {");
      EmitExceptionHandler(sb, call, "__assertion", bodyText, "null, null, null", "          ");
      sb.AppendLine("        }");
      sb.AppendLine($"      }}){forwardedArgs});");
      sb.AppendLine("    }");
    }

    /// <summary>
    /// Emits an interceptor for an Assert.Throws call with an exception-predicate lambda.
    /// Behavior is delegated to the runtime (GeneratedAssert.ThrowsIntercepted); the
    /// interceptor contributes a factory that decomposes the classified predicate body
    /// with the thrown exception bound to its parameter. The predicate parameter is named
    /// __assertion because compiled operands read captured locals from that delegate.
    /// </summary>
    private static void EmitThrowsInterceptor(StringBuilder sb, InterceptedCall call, int index)
    {
      var exceptionType = call.ThrowsExceptionTypeFqn ?? "global::System.Exception";

      var actionType = call.ThrowsActionKind switch
      {
        ThrowsActionKind.Action => "global::System.Action",
        ThrowsActionKind.FuncObject => "global::System.Func<object>",
        _ => "global::System.Func<global::System.Threading.Tasks.Task>",
      };

      var isAsync = call.ThrowsActionKind == ThrowsActionKind.FuncTask;
      var returnType = isAsync ? $"global::System.Threading.Tasks.Task<{exceptionType}>" : exceptionType;

      var actionArg = call.ThrowsActionKind == ThrowsActionKind.FuncObject
        ? "new global::System.Action(() => { _ = __action(); })"
        : "__action";

      var expectedTypeArg = call.ThrowsExceptionTypeFqn != null ? $"typeof({call.ThrowsExceptionTypeFqn})" : "null";
      var runtimeEntry = isAsync ? "ThrowsInterceptedAsync" : "ThrowsIntercepted";
      var awaitKeyword = isAsync ? "await " : "";

      sb.AppendLine($"    // {call.DisplayLocation}");
      sb.AppendLine("    [global::System.Diagnostics.StackTraceHidden]");
      sb.AppendLine($"    [global::System.Runtime.CompilerServices.InterceptsLocation({call.LocationVersion}, {Quote(call.LocationData)})]");
      sb.AppendLine($"    public static {(isAsync ? "async " : "")}{returnType} Throws{index}({actionType} __action, global::System.Func<{exceptionType}, bool> __assertion, string __actionExpr, string __exceptionExpr)");
      sb.AppendLine("    {");
      EmitCaptureDecls(sb, call, "__assertion", "      ");
      sb.AppendLine($"      return ({exceptionType}){awaitKeyword}global::Assertive.Runtime.GeneratedAssert.{runtimeEntry}(");
      sb.AppendLine($"        {actionArg},");
      sb.AppendLine($"        {expectedTypeArg},");
      sb.AppendLine($"        __assertion == null ? null : new global::System.Func<global::System.Exception, bool>(__e => __assertion(({exceptionType})__e)),");
      sb.AppendLine("        __actionExpr, __exceptionExpr,");
      sb.AppendLine($"        {BuildSubRenderer(call.AllSubCall, Quote(call.BodySource), "        ")});");
      sb.AppendLine("    }");
    }

    /// <summary>
    /// Emits the body of the exception filter handler: re-declares the captured locals
    /// (the try block's are out of scope) and reports the exception, with cause
    /// attribution when the call site has recorded exception steps.
    /// </summary>
    private static void EmitExceptionHandler(StringBuilder sb, InterceptedCall call, string delegateName, string assertionTextArg, string tailArgs, string indent)
    {
      EmitCaptureDecls(sb, call, delegateName, indent);

      var steps = call.ExceptionStepsSource ?? "null";

      sb.AppendLine($"{indent}throw global::Assertive.Runtime.GeneratedAssert.EvaluationFailure({assertionTextArg}, __ex,");
      sb.AppendLine($"{indent}  {steps},");
      sb.AppendLine($"{indent}  {BuildLocalsArray(call)},");
      sb.AppendLine($"{indent}  {tailArgs});");
    }

    private static void EmitCaptureDecls(StringBuilder sb, InterceptedCall call, string delegateName, string indent)
    {
      foreach (var local in call.CapturedLocals)
      {
        // Unnameable types are read as object; member access on them happens reflectively.
        sb.AppendLine(local.Type != null
          ? $"{indent}{local.Type} {local.Name} = ({local.Type})global::Assertive.Runtime.GeneratedAssert.GetCapturedValue({delegateName}, {Quote(local.Name)});"
          : $"{indent}object {local.Name} = global::Assertive.Runtime.GeneratedAssert.GetCapturedValue({delegateName}, {Quote(local.Name)});");
      }
    }

    /// <summary>
    /// Locals that are themselves a whole operand are already displayed as the operand
    /// value; everything else captured shows up under LOCALS (mirrors LocalsProvider).
    /// </summary>
    private static string BuildLocalsArray(InterceptedCall call)
      => BuildLocalsArray(call.CapturedLocals, call.LeftDisplay, call.RightDisplay);

    private static string BuildLocalsArray(IEnumerable<(string Name, string? Type)> locals, string leftDisplay, string rightDisplay)
    {
      var displayedLocals = locals
        .Where(l => l.Name != leftDisplay.Trim() && l.Name != rightDisplay.Trim())
        .ToList();

      return displayedLocals.Count == 0
        ? "global::System.Array.Empty<(string, object)>()"
        : $"new (string, object)[] {{ {string.Join(", ", displayedLocals.Select(l => $"({Quote(l.Name)}, (object){l.Name})"))} }}";
    }

    /// <summary>
    /// Emits the shared evaluation core. The original delegate decides pass/fail — exactly
    /// one evaluation, no generated comparison semantics. Only on failure are the operands
    /// re-evaluated (typed or reflectively) for the decomposed report, mirroring how the
    /// expression-based pipeline re-evaluated sub-expressions during failure analysis.
    /// </summary>
    private static void EmitEvaluation(StringBuilder sb, InterceptedCall call, string delegateName, string assertionTextArg, string tailArgs, string indent)
    {
      sb.AppendLine($"{indent}if ({delegateName}()) return;");

      EmitCaptureDecls(sb, call, delegateName, indent);

      // The Bool/Opaque/Split patterns need no operand values (the delegate already
      // evaluated the body); everything else re-evaluates the operand(s) it reports on.
      if (call.Kind is not (InterceptionKind.Bool or InterceptionKind.Opaque or InterceptionKind.Split))
      {
        sb.AppendLine($"{indent}var __left = {call.LeftSource};");
      }

      if (HasRightOperand(call.Kind))
      {
        sb.AppendLine($"{indent}var __right = {call.RightSource};");
      }

      var localsArray = BuildLocalsArray(call);
      var tail = $"{localsArray},\n{indent}  {tailArgs}";

      // Runtime-registered custom patterns take precedence over the built-in decomposition
      // (the old FallbackPattern consulted them first).
      if (call.CustomProbeSource != null)
      {
        sb.AppendLine($"{indent}if (global::Assertive.Runtime.GeneratedAssert.TryCustomFailure({assertionTextArg},");
        sb.AppendLine($"{indent}  {call.CustomProbeSource},");
        sb.AppendLine($"{indent}  {tail}) is {{ }} __custom)");
        sb.AppendLine($"{indent}{{");
        sb.AppendLine($"{indent}  throw __custom;");
        sb.AppendLine($"{indent}}}");
      }

      if (call.Kind == InterceptionKind.Split)
      {
        sb.AppendLine($"{indent}throw global::Assertive.Runtime.GeneratedAssert.SplitFailure({assertionTextArg},");
        sb.AppendLine($"{indent}  {BuildPartInitializer(call.SplitRoot!, indent + "  ", tailArgs)},");
        sb.AppendLine($"{indent}  {tailArgs});");
        return;
      }

      sb.AppendLine($"{indent}throw global::Assertive.Runtime.GeneratedAssert.{BuildFailureInvocation(call, assertionTextArg, indent, tail, "__left", "__right")});");
    }

    /// <summary>
    /// Emits the Assertive.Runtime.AssertionPart tree for a split (logically-composed)
    /// assertion body. Leaves re-evaluate their pasted source and report through their
    /// classified decomposition (custom patterns first), with leaf-scoped exception steps
    /// and locals.
    /// </summary>
    private static string BuildPartInitializer(SplitPart part, string indent, string tailArgs)
    {
      const string partType = "global::Assertive.Runtime.AssertionPart";
      const string partKind = "global::Assertive.Runtime.AssertionPartKind";
      const string runtime = "global::Assertive.Runtime.GeneratedAssert";

      if (part.Kind != "Leaf")
      {
        return $"new {partType}\n{indent}{{\n" +
               $"{indent}  Kind = {partKind}.{part.Kind},\n" +
               $"{indent}  Left = {BuildPartInitializer(part.Left!, indent + "  ", tailArgs)},\n" +
               $"{indent}  Right = {BuildPartInitializer(part.Right!, indent + "  ", tailArgs)},\n" +
               $"{indent}}}";
      }

      var leafText = Quote(part.LeafSource);
      var inner = indent + "  ";

      var localsArray = BuildLocalsArray(part.Locals, part.SubCall?.LeftDisplay ?? "", part.SubCall?.RightDisplay ?? "");
      var leafTail = $"{localsArray}, {tailArgs}";

      // Custom patterns take precedence over the leaf's own decomposition.
      var probe = part.ProbeSource != null
        ? $"{runtime}.TryCustomFailure({leafText}, {part.ProbeSource}, {leafTail}) ?? "
        : "";

      string failure;

      if (part.SubCall is { } sub)
      {
        var body = new StringBuilder();
        body.Append($"(global::System.Func<global::System.Exception>)(() =>\n{inner}{{\n");

        if (sub.Kind is not (InterceptionKind.Bool or InterceptionKind.Opaque))
        {
          body.Append($"{inner}  var __subLeft = {sub.LeftSource};\n");
        }

        if (HasRightOperand(sub.Kind))
        {
          body.Append($"{inner}  var __subRight = {sub.RightSource};\n");
        }

        var subTail = $"{localsArray},\n{inner}    {tailArgs}";

        body.Append($"{inner}  return {probe}{runtime}.{BuildFailureInvocation(sub, leafText, inner + "  ", subTail, "__subLeft", "__subRight")});\n");
        body.Append($"{inner}}})");
        failure = body.ToString();
      }
      else
      {
        failure = $"() => {probe}{runtime}.Failure({leafText}, {leafTail})";
      }

      return $"new {partType}\n{indent}{{\n" +
             $"{indent}  Kind = {partKind}.Leaf,\n" +
             $"{indent}  Source = {leafText},\n" +
             $"{indent}  Condition = () => (bool)(object)({part.ConditionSource}),\n" +
             $"{indent}  Failure = {failure},\n" +
             $"{indent}  ExceptionFailure = (__leafEx) => {runtime}.EvaluationFailure({leafText}, __leafEx, {part.StepsSource ?? "null"}, {localsArray}, {tailArgs}),\n" +
             $"{indent}}}";
    }

    private static bool HasRightOperand(InterceptionKind kind)
      => kind is InterceptionKind.Equality or InterceptionKind.ReferenceEquals
        or InterceptionKind.Comparison or InterceptionKind.Length
        or InterceptionKind.Contains or InterceptionKind.StartsEndsWith or InterceptionKind.SequenceEqual;

    /// <summary>
    /// The GeneratedAssert.XFailure(...) invocation for a classified call, parameterized on
    /// the operand local names so it serves both the top-level throw and the per-item
    /// sub-failure renderers of the All pattern.
    /// </summary>
    private static string BuildFailureInvocation(InterceptedCall call, string assertionTextArg, string indent, string tail, string left, string right)
    {
      var negated = call.Negated ? "true" : "false";
      var rightIsConstant = call.RightIsConstant ? "true" : "false";

      return call.Kind switch
      {
        InterceptionKind.Equality =>
          $"EqualityFailure(\n{indent}  {assertionTextArg},\n{indent}  {Quote(call.LeftDisplay)}, (object){left},\n{indent}  {Quote(call.RightDisplay)}, (object){right},\n{indent}  {rightIsConstant}, {negated},\n{indent}  {tail}",
        InterceptionKind.ReferenceEquals =>
          $"ReferenceEqualsFailure(\n{indent}  {assertionTextArg},\n{indent}  {Quote(call.LeftDisplay)}, (object){left},\n{indent}  {Quote(call.RightDisplay)}, (object){right},\n{indent}  {negated},\n{indent}  {tail}",
        InterceptionKind.Bool =>
          $"BoolFailure(\n{indent}  {assertionTextArg},\n{indent}  {Quote(call.LeftDisplay)}, {negated},\n{indent}  {tail}",
        InterceptionKind.Null =>
          $"NullFailure(\n{indent}  {assertionTextArg},\n{indent}  {Quote(call.LeftDisplay)}, (object){left}, {negated},\n{indent}  {tail}",
        InterceptionKind.HasValue =>
          $"HasValueFailure(\n{indent}  {assertionTextArg},\n{indent}  {Quote(call.LeftDisplay)}, (object){left}, {negated},\n{indent}  {tail}",
        InterceptionKind.Is =>
          $"IsTypeFailure(\n{indent}  {assertionTextArg},\n{indent}  {Quote(call.LeftDisplay)}, (object){left}, {call.TypeAccessor}, {negated},\n{indent}  {tail}",
        InterceptionKind.Comparison =>
          $"ComparisonFailure(\n{indent}  {assertionTextArg},\n{indent}  {Quote(call.LeftDisplay)}, (object){left},\n{indent}  {Quote(call.RightDisplay)}, (object){right},\n{indent}  {rightIsConstant}, {Quote(call.ComparisonLabel ?? "")},\n{indent}  {tail}",
        InterceptionKind.Length =>
          $"LengthFailure(\n{indent}  {assertionTextArg},\n{indent}  {Quote(call.OperandDisplay)}, {(call.FilterSource != null ? Quote(call.FilterSource) : "null")}, {Quote(call.CountLabel)}, {Quote(call.ComparisonLabel ?? "")},\n{indent}  (object){left},\n{indent}  {Quote(call.RightDisplay)}, (object){right}, {rightIsConstant},\n{indent}  {tail}",
        InterceptionKind.Contains =>
          $"ContainsFailure(\n{indent}  {assertionTextArg},\n{indent}  {Quote(call.LeftDisplay)}, (object){left},\n{indent}  {Quote(call.RightDisplay)}, (object){right},\n{indent}  {rightIsConstant}, {(call.StringInstance ? "true" : "false")}, {negated},\n{indent}  {tail}",
        InterceptionKind.StartsEndsWith =>
          $"StartsEndsWithFailure(\n{indent}  {assertionTextArg},\n{indent}  {Quote(call.LeftDisplay)}, (object){left},\n{indent}  {Quote(call.RightDisplay)}, (object){right},\n{indent}  {rightIsConstant}, {Quote(call.ComparisonLabel ?? "")}, {negated},\n{indent}  {tail}",
        InterceptionKind.Any =>
          $"AnyFailure(\n{indent}  {assertionTextArg},\n{indent}  {Quote(call.OperandDisplay)}, {(call.FilterSource != null ? Quote(call.FilterSource) : "null")}, {negated}, {left},\n{indent}  {tail}",
        InterceptionKind.SequenceEqual =>
          $"SequenceEqualFailure(\n{indent}  {assertionTextArg},\n{indent}  {Quote(call.LeftDisplay)}, (object){left},\n{indent}  {Quote(call.RightDisplay)}, (object){right},\n{indent}  {(call.ComparerSource != null ? $"(object)({call.ComparerSource})" : "null")}, {call.TypeAccessor ?? "null"},\n{indent}  {tail}",
        InterceptionKind.All =>
          $"AllFailure(\n{indent}  {assertionTextArg},\n{indent}  {Quote(call.OperandDisplay)}, {Quote(call.FilterSource ?? "")}, {(call.CollectionIsMethodCall ? "true" : "false")}, (object){left}, {negated},\n{indent}  {call.AllFilterFunc ?? "null"},\n{indent}  {BuildSubRenderer(call.AllSubCall, Quote(call.FilterSource ?? ""), indent)},\n{indent}  {tail}",
        InterceptionKind.Opaque =>
          $"Failure(\n{indent}  {assertionTextArg},\n{indent}  {tail}",
        _ => throw new System.InvalidOperationException($"Unhandled kind {call.Kind}"),
      };
    }

    /// <summary>
    /// A bound sub-failure factory: evaluates the classified sub-assertion's operands with
    /// the bound value (an All item, or the exception caught by Throws) and builds the
    /// corresponding failure exception. Its expected/actual data becomes the sub-message.
    /// </summary>
    private static string BuildSubRenderer(InterceptedCall? sub, string assertionTextArg, string indent)
    {
      if (sub == null)
      {
        return "null";
      }

      var inner = indent + "    ";
      var renderer = new StringBuilder();

      renderer.Append("(global::System.Func<object, int, global::System.Exception>)((__item, __idx) =>\n");
      renderer.Append($"{indent}  {{\n");

      if (sub.Kind is not (InterceptionKind.Bool or InterceptionKind.Opaque))
      {
        renderer.Append($"{inner}var __subLeft = {sub.LeftSource};\n");
      }

      if (HasRightOperand(sub.Kind))
      {
        renderer.Append($"{inner}var __subRight = {sub.RightSource};\n");
      }

      var subTail = $"global::System.Array.Empty<(string, object)>(),\n{inner}  null, null, null";

      renderer.Append($"{inner}return global::Assertive.Runtime.GeneratedAssert.{BuildFailureInvocation(sub, assertionTextArg, inner, subTail, "__subLeft", "__subRight")});\n");
      renderer.Append($"{indent}  }})");

      return renderer.ToString();
    }

    private static string Quote(string text) => SymbolDisplay.FormatLiteral(text, quote: true);

    private static string StableHash(string text)
    {
      // FNV-1a; string.GetHashCode is not stable across runs on modern runtimes.
      unchecked
      {
        var hash = 2166136261u;

        foreach (var c in text)
        {
          hash = (hash ^ c) * 16777619u;
        }

        return hash.ToString("x8");
      }
    }
  }

  internal enum ThatOverload
  {
    Context,
    MessageContext,
  }

  /// <summary>The shape of an intercepted Assert.Throws first parameter.</summary>
  internal enum ThrowsActionKind
  {
    Action,
    FuncObject,
    FuncTask,
  }

  internal enum InterceptionKind
  {
    Equality,
    ReferenceEquals,
    Bool,
    Null,
    HasValue,
    Is,
    Comparison,
    Length,
    Contains,
    StartsEndsWith,
    Any,
    SequenceEqual,
    All,

    /// <summary>
    /// An Assert.Throws call with an exception-predicate lambda; the predicate body is
    /// classified as a sub-assertion bound to the thrown exception.
    /// </summary>
    ThrowsPredicate,

    /// <summary>
    /// A logically-composed body (`a &amp;&amp; b`, `a &amp; b`, ...): split into leaf assertions
    /// that report individually with operator semantics.
    /// </summary>
    Split,

    /// <summary>
    /// Not a decomposable form: the false path reports source text + locals only, but the
    /// call is still intercepted so the exception path gets cause attribution.
    /// </summary>
    Opaque,
  }

  internal sealed class InterceptedCall
  {
    public int LocationVersion;
    public string LocationData = "";
    public string DisplayLocation = "";
    public string FilePath = "";
    public ThatOverload Overload;
    public WrapperModel? Wrapper;
    public InterceptionKind Kind;

    /// <summary>Captured locals to declare; Type is null for unnameable types (read as object).</summary>
    public List<(string Name, string? Type)> CapturedLocals { get; } = new();

    public string BodySource = "";
    public string LeftSource = "";
    public string RightSource = "";
    public string LeftDisplay = "";
    public string RightDisplay = "";

    /// <summary>
    /// Message-level negation. Per kind: Equality reads "should not equal", Null means
    /// "expected null", Bool/HasValue/Is/ReferenceEquals negate their message.
    /// </summary>
    public bool Negated;
    public bool RightIsConstant;

    /// <summary>Comparison/Length: "less than", "equal to", ...</summary>
    public string? ComparisonLabel;

    /// <summary>Length: "Length" or "Count".</summary>
    public string CountLabel = "";

    /// <summary>Length: the collection/string operand (receiver of the Length/Count access).</summary>
    public string OperandDisplay = "";

    /// <summary>Length: source of the Count(...) filter lambda body, if any.</summary>
    public string? FilterSource;

    /// <summary>Is: C# expression evaluating to the checked System.Type. SequenceEqual: the element type.</summary>
    public string? TypeAccessor;

    /// <summary>Contains: whether the receiver is a string (substring wording + hints).</summary>
    public bool StringInstance;

    /// <summary>SequenceEqual: compiled comparer argument, if present.</summary>
    public string? ComparerSource;

    /// <summary>All: whether the collection operand is itself a method call (changes the per-item prefix).</summary>
    public bool CollectionIsMethodCall;

    /// <summary>All: compiled `(item, index) => bool` filter used to find the failing items.</summary>
    public string? AllFilterFunc;

    /// <summary>All: the filter body classified as a per-item sub-assertion, if decomposable.</summary>
    public InterceptedCall? AllSubCall;

    /// <summary>
    /// `new ExceptionStep[] { ... }` source for exception-cause attribution on the
    /// failure path, or null when the body has no throw-capable sub-expressions.
    /// </summary>
    public string? ExceptionStepsSource;

    /// <summary>
    /// `new CustomPatternProbe { ... }` source for runtime custom-pattern matching, or
    /// null when the body root is not a method call / property access.
    /// </summary>
    public string? CustomProbeSource;

    /// <summary>ThrowsPredicate: the shape of the intercepted Throws action parameter.</summary>
    public ThrowsActionKind ThrowsActionKind;

    /// <summary>ThrowsPredicate: the expected exception type, or null for the non-generic overloads.</summary>
    public string? ThrowsExceptionTypeFqn;

    /// <summary>Split: the part tree of a logically-composed body.</summary>
    public SplitPart? SplitRoot;
  }

  /// <summary>
  /// Generator-side node of a logically-composed assertion body; emitted as an
  /// Assertive.Runtime.AssertionPart tree.
  /// </summary>
  internal sealed class SplitPart
  {
    /// <summary>AssertionPartKind member name: Leaf, AndAlso, And, OrElse, Or.</summary>
    public string Kind = "Leaf";

    public SplitPart? Left;
    public SplitPart? Right;

    public string LeafSource = "";

    /// <summary>Compiled re-evaluation of the leaf.</summary>
    public string? ConditionSource;

    /// <summary>The leaf classified as its own assertion, or null (source-text report).</summary>
    public InterceptedCall? SubCall;

    /// <summary>Exception steps scoped to this leaf, for re-evaluation throws.</summary>
    public string? StepsSource;

    /// <summary>Custom-pattern probe for the leaf root, if it is a call/property.</summary>
    public string? ProbeSource;

    /// <summary>Captured locals introduced by this leaf's compilations.</summary>
    public List<(string Name, string? Type)> Locals { get; } = new();
  }

  /// <summary>An [AssertionWrapper] method pair (see AssertionWrapperAttribute in Assertive).</summary>
  internal sealed class WrapperModel
  {
    public string MethodName = "";
    public string ContainingTypeFqn = "";
    public bool IsStatic;
    public string ReturnTypeFqn = "void";
    public List<string> ExtraParameterTypes { get; } = new();
  }
}
