using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace Assertive.Generators
{
  /// <summary>
  /// Intercepts Assert.That / DSL.Assert / [AssertionWrapper] call sites whose lambda body
  /// is a binary ==/!= comparison, replacing delegate evaluation with directly emitted,
  /// typed C#: captured locals are read from the delegate's closure, each operand is
  /// evaluated exactly once, and failures are reported through
  /// GeneratedAssert.EqualityFailure with captured values (EqualsPattern parity).
  ///
  /// There is no expression-tree fallback: call sites outside the whitelist run the plain
  /// delegate and report from source text only, until their patterns are ported.
  /// </summary>
  [Generator]
  public sealed class EqualsInterceptorGenerator : IIncrementalGenerator
  {
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
      var calls = context.SyntaxProvider.CreateSyntaxProvider(
          // Cheap syntax pre-filter: any invocation whose first argument is a zero-parameter
          // lambda literal. The transform's symbol checks reject everything else.
          predicate: static (node, _) => node is InvocationExpressionSyntax invocation
            && invocation.ArgumentList.Arguments.Count > 0
            && invocation.ArgumentList.Arguments[0].Expression is ParenthesizedLambdaExpressionSyntax { ParameterList.Parameters.Count: 0 },
          transform: static (ctx, ct) => CallSiteAnalyzer.Analyze(ctx, ct))
        .Where(static c => c is not null);

      context.RegisterSourceOutput(calls.Collect(), static (spc, all) => Emit(spc, all!));
    }

    private static void Emit(SourceProductionContext spc, ImmutableArray<InterceptedCall?> calls)
    {
      foreach (var fileGroup in calls.Where(c => c != null).GroupBy(c => c!.FilePath))
      {
        // Readable, collision-free: source file stem + stable hash of the full path.
        var stem = new string(System.IO.Path.GetFileNameWithoutExtension(fileGroup.Key)
          .Where(char.IsLetterOrDigit).ToArray());
        var classSuffix = $"{stem}_{StableHash(fileGroup.Key)}";
        var sb = new StringBuilder();

        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable disable");
        sb.AppendLine("#pragma warning disable");
        sb.AppendLine();
        sb.AppendLine("namespace System.Runtime.CompilerServices");
        sb.AppendLine("{");
        sb.AppendLine("  [global::System.AttributeUsage(global::System.AttributeTargets.Method, AllowMultiple = true)]");
        sb.AppendLine("  file sealed class InterceptsLocationAttribute : global::System.Attribute");
        sb.AppendLine("  {");
        sb.AppendLine("    public InterceptsLocationAttribute(int version, string data)");
        sb.AppendLine("    {");
        sb.AppendLine("      _ = version;");
        sb.AppendLine("      _ = data;");
        sb.AppendLine("    }");
        sb.AppendLine("  }");
        sb.AppendLine("}");
        sb.AppendLine();
        sb.AppendLine("namespace Assertive.Generated");
        sb.AppendLine("{");
        sb.AppendLine($"  internal static class AssertThatInterceptors_{classSuffix}");
        sb.AppendLine("  {");

        var index = 0;

        foreach (var call in fileGroup)
        {
          if (call!.Wrapper != null)
          {
            EmitWrapperInterceptor(sb, call, index++);
          }
          else
          {
            EmitThatInterceptor(sb, call, index++);
          }

          sb.AppendLine();
        }

        sb.AppendLine("  }");
        sb.AppendLine("}");

        spc.AddSource($"AssertThatInterceptors_{classSuffix}.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
      }
    }

    private static void EmitThatInterceptor(StringBuilder sb, InterceptedCall call, int index)
    {
      var parameters = call.Overload switch
      {
        ThatOverload.Context => "global::System.Func<bool> __assertion, global::System.Func<object> __context, string __expr, string __contextExpr",
        _ => "global::System.Func<bool> __assertion, object __message, global::System.Func<object> __context, string __expr, string __contextExpr",
      };

      var messageArg = call.Overload is ThatOverload.MessageContext ? "__message" : "null";
      var contextArg = "__context";
      var contextExprArg = "__contextExpr";

      sb.AppendLine($"    // {call.DisplayLocation}");
      sb.AppendLine("    [global::System.Diagnostics.StackTraceHidden]");
      sb.AppendLine($"    [global::System.Runtime.CompilerServices.InterceptsLocation({call.LocationVersion}, {Quote(call.LocationData)})]");
      sb.AppendLine($"    public static void That{index}({parameters})");
      sb.AppendLine("    {");
      sb.AppendLine("      global::Assertive.Runtime.GeneratedAssert.MarkIntercepted();");
      sb.AppendLine("      try");
      sb.AppendLine("      {");
      EmitEvaluation(sb, call, "__assertion", "__expr", $"{messageArg}, {contextArg}, {contextExprArg}", "        ");
      sb.AppendLine("      }");
      sb.AppendLine("      catch (global::System.Exception __ex) when (!global::Assertive.Runtime.GeneratedAssert.IsAssertionFailure(__ex))");
      sb.AppendLine("      {");
      sb.AppendLine($"        throw global::Assertive.Runtime.GeneratedAssert.EvaluationFailure(__expr, __ex, {messageArg}, {contextArg}, {contextExprArg});");
      sb.AppendLine("      }");
      sb.AppendLine("    }");
    }

    /// <summary>
    /// Emits an interceptor for an [AssertionWrapper] call site: routes to the wrapper's
    /// AssertionHandle overload carrying a generated assertion action. Instance wrappers
    /// are intercepted with an extension method (receiver as first parameter).
    /// </summary>
    private static void EmitWrapperInterceptor(StringBuilder sb, InterceptedCall call, int index)
    {
      var wrapper = call.Wrapper!;

      var parameters = new List<string>();

      if (!wrapper.IsStatic)
      {
        parameters.Add($"this {wrapper.ContainingTypeFqn} __receiver");
      }

      parameters.Add("global::System.Func<bool> __assertion");

      for (var i = 0; i < wrapper.ExtraParameterTypes.Count; i++)
      {
        parameters.Add($"{wrapper.ExtraParameterTypes[i]} __p{i}");
      }

      var forwardedArgs = string.Concat(Enumerable.Range(0, wrapper.ExtraParameterTypes.Count).Select(i => $", __p{i}"));
      var target = wrapper.IsStatic ? wrapper.ContainingTypeFqn : "__receiver";
      var returnKeyword = wrapper.ReturnTypeFqn == "void" ? "" : "return ";
      var bodyText = Quote(call.BodySource);

      sb.AppendLine($"    // {call.DisplayLocation}");
      sb.AppendLine("    [global::System.Diagnostics.StackTraceHidden]");
      sb.AppendLine($"    [global::System.Runtime.CompilerServices.InterceptsLocation({call.LocationVersion}, {Quote(call.LocationData)})]");
      sb.AppendLine($"    public static {wrapper.ReturnTypeFqn} Wrapper{index}({string.Join(", ", parameters)})");
      sb.AppendLine("    {");
      sb.AppendLine("      global::Assertive.Runtime.GeneratedAssert.MarkIntercepted();");
      sb.AppendLine($"      {returnKeyword}{target}.{wrapper.MethodName}(global::Assertive.AssertionHandle.Generated(() =>");
      sb.AppendLine("      {");
      sb.AppendLine("        try");
      sb.AppendLine("        {");
      EmitEvaluation(sb, call, "__assertion", bodyText, "null, null, null", "          ");
      sb.AppendLine("        }");
      sb.AppendLine("        catch (global::System.Exception __ex) when (!global::Assertive.Runtime.GeneratedAssert.IsAssertionFailure(__ex))");
      sb.AppendLine("        {");
      sb.AppendLine($"          throw global::Assertive.Runtime.GeneratedAssert.EvaluationFailure({bodyText}, __ex, null, null, null);");
      sb.AppendLine("        }");
      sb.AppendLine($"      }}){forwardedArgs});");
      sb.AppendLine("    }");
    }

    /// <summary>
    /// Emits the shared evaluation core. The original delegate decides pass/fail — exactly
    /// one evaluation, no generated comparison semantics. Only on failure are the operands
    /// re-evaluated (typed or reflectively) for the decomposed report, mirroring how the
    /// expression-based pipeline re-evaluated sub-expressions during failure analysis.
    /// </summary>
    private static void EmitEvaluation(StringBuilder sb, InterceptedCall call, string delegateName, string assertionTextArg, string tailArgs, string indent)
    {
      sb.AppendLine($"{indent}if ({delegateName}()) return;");

      foreach (var local in call.CapturedLocals)
      {
        // Unnameable types are read as object; member access on them happens reflectively.
        sb.AppendLine(local.Type != null
          ? $"{indent}{local.Type} {local.Name} = ({local.Type})global::Assertive.Runtime.GeneratedAssert.GetCapturedValue({delegateName}, {Quote(local.Name)});"
          : $"{indent}object {local.Name} = global::Assertive.Runtime.GeneratedAssert.GetCapturedValue({delegateName}, {Quote(local.Name)});");
      }

      // The Bool pattern needs no operand values (the delegate already evaluated the
      // member); everything else re-evaluates the operand(s) it reports on.
      if (call.Kind != InterceptionKind.Bool)
      {
        sb.AppendLine($"{indent}var __left = {call.LeftSource};");
      }

      var hasRight = call.Kind is InterceptionKind.Equality or InterceptionKind.ReferenceEquals
        or InterceptionKind.Comparison or InterceptionKind.Length
        or InterceptionKind.Contains or InterceptionKind.StartsEndsWith or InterceptionKind.SequenceEqual;

      if (hasRight)
      {
        sb.AppendLine($"{indent}var __right = {call.RightSource};");
      }

      // Locals that are themselves a whole operand are already displayed as the operand
      // value; everything else captured shows up under LOCALS (mirrors LocalsProvider).
      var displayedLocals = call.CapturedLocals
        .Where(l => l.Name != call.LeftDisplay.Trim() && l.Name != call.RightDisplay.Trim())
        .ToList();

      var localsArray = displayedLocals.Count == 0
        ? "global::System.Array.Empty<(string, object)>()"
        : $"new (string, object)[] {{ {string.Join(", ", displayedLocals.Select(l => $"({Quote(l.Name)}, (object){l.Name})"))} }}";

      var negated = call.Negated ? "true" : "false";
      var rightIsConstant = call.RightIsConstant ? "true" : "false";
      var tail = $"{localsArray},\n{indent}  {tailArgs}";

      var throwArgs = call.Kind switch
      {
        InterceptionKind.Equality =>
          $"EqualityFailure(\n{indent}  {assertionTextArg},\n{indent}  {Quote(call.LeftDisplay)}, (object)__left,\n{indent}  {Quote(call.RightDisplay)}, (object)__right,\n{indent}  {rightIsConstant}, {negated},\n{indent}  {tail}",
        InterceptionKind.ReferenceEquals =>
          $"ReferenceEqualsFailure(\n{indent}  {assertionTextArg},\n{indent}  {Quote(call.LeftDisplay)}, (object)__left,\n{indent}  {Quote(call.RightDisplay)}, (object)__right,\n{indent}  {negated},\n{indent}  {tail}",
        InterceptionKind.Bool =>
          $"BoolFailure(\n{indent}  {assertionTextArg},\n{indent}  {Quote(call.LeftDisplay)}, {negated},\n{indent}  {tail}",
        InterceptionKind.Null =>
          $"NullFailure(\n{indent}  {assertionTextArg},\n{indent}  {Quote(call.LeftDisplay)}, (object)__left, {negated},\n{indent}  {tail}",
        InterceptionKind.HasValue =>
          $"HasValueFailure(\n{indent}  {assertionTextArg},\n{indent}  {Quote(call.LeftDisplay)}, (object)__left, {negated},\n{indent}  {tail}",
        InterceptionKind.Is =>
          $"IsTypeFailure(\n{indent}  {assertionTextArg},\n{indent}  {Quote(call.LeftDisplay)}, (object)__left, {call.TypeAccessor}, {negated},\n{indent}  {tail}",
        InterceptionKind.Comparison =>
          $"ComparisonFailure(\n{indent}  {assertionTextArg},\n{indent}  {Quote(call.LeftDisplay)}, (object)__left,\n{indent}  {Quote(call.RightDisplay)}, (object)__right,\n{indent}  {rightIsConstant}, {Quote(call.ComparisonLabel ?? "")},\n{indent}  {tail}",
        InterceptionKind.Length =>
          $"LengthFailure(\n{indent}  {assertionTextArg},\n{indent}  {Quote(call.OperandDisplay)}, {(call.FilterSource != null ? Quote(call.FilterSource) : "null")}, {Quote(call.CountLabel)}, {Quote(call.ComparisonLabel ?? "")},\n{indent}  (object)__left,\n{indent}  {Quote(call.RightDisplay)}, (object)__right, {rightIsConstant},\n{indent}  {tail}",
        InterceptionKind.Contains =>
          $"ContainsFailure(\n{indent}  {assertionTextArg},\n{indent}  {Quote(call.LeftDisplay)}, (object)__left,\n{indent}  {Quote(call.RightDisplay)}, (object)__right,\n{indent}  {rightIsConstant}, {(call.StringInstance ? "true" : "false")}, {negated},\n{indent}  {tail}",
        InterceptionKind.StartsEndsWith =>
          $"StartsEndsWithFailure(\n{indent}  {assertionTextArg},\n{indent}  {Quote(call.LeftDisplay)}, (object)__left,\n{indent}  {Quote(call.RightDisplay)}, (object)__right,\n{indent}  {rightIsConstant}, {Quote(call.ComparisonLabel ?? "")}, {negated},\n{indent}  {tail}",
        InterceptionKind.Any =>
          $"AnyFailure(\n{indent}  {assertionTextArg},\n{indent}  {Quote(call.OperandDisplay)}, {(call.FilterSource != null ? Quote(call.FilterSource) : "null")}, {negated}, __left,\n{indent}  {tail}",
        InterceptionKind.SequenceEqual =>
          $"SequenceEqualFailure(\n{indent}  {assertionTextArg},\n{indent}  {Quote(call.LeftDisplay)}, (object)__left,\n{indent}  {Quote(call.RightDisplay)}, (object)__right,\n{indent}  {(call.ComparerSource != null ? $"(object)({call.ComparerSource})" : "null")}, {call.TypeAccessor ?? "null"},\n{indent}  {tail}",
        _ => throw new System.InvalidOperationException($"Unhandled kind {call.Kind}"),
      };

      sb.AppendLine($"{indent}throw global::Assertive.Runtime.GeneratedAssert.{throwArgs});");
    }

    private static string Quote(string text) => SymbolDisplay.FormatLiteral(text, quote: true);

    private static string StableHash(string text)
    {
      // FNV-1a; string.GetHashCode is not stable across runs on modern runtimes.
      unchecked
      {
        var hash = 2166136261u;

        foreach (var c in text)
        {
          hash = (hash ^ c) * 16777619u;
        }

        return hash.ToString("x8");
      }
    }
  }

  internal enum ThatOverload
  {
    Context,
    MessageContext,
  }

  internal enum InterceptionKind
  {
    Equality,
    ReferenceEquals,
    Bool,
    Null,
    HasValue,
    Is,
    Comparison,
    Length,
    Contains,
    StartsEndsWith,
    Any,
    SequenceEqual,
  }

  internal sealed class InterceptedCall
  {
    public int LocationVersion;
    public string LocationData = "";
    public string DisplayLocation = "";
    public string FilePath = "";
    public ThatOverload Overload;
    public WrapperModel? Wrapper;
    public InterceptionKind Kind;

    /// <summary>Captured locals to declare; Type is null for unnameable types (read as object).</summary>
    public List<(string Name, string? Type)> CapturedLocals { get; } = new();

    public string BodySource = "";
    public string LeftSource = "";
    public string RightSource = "";
    public string LeftDisplay = "";
    public string RightDisplay = "";

    /// <summary>
    /// Message-level negation. Per kind: Equality reads "should not equal", Null means
    /// "expected null", Bool/HasValue/Is/ReferenceEquals negate their message.
    /// </summary>
    public bool Negated;
    public bool RightIsConstant;

    /// <summary>Comparison/Length: "less than", "equal to", ...</summary>
    public string? ComparisonLabel;

    /// <summary>Length: "Length" or "Count".</summary>
    public string CountLabel = "";

    /// <summary>Length: the collection/string operand (receiver of the Length/Count access).</summary>
    public string OperandDisplay = "";

    /// <summary>Length: source of the Count(...) filter lambda body, if any.</summary>
    public string? FilterSource;

    /// <summary>Is: C# expression evaluating to the checked System.Type. SequenceEqual: the element type.</summary>
    public string? TypeAccessor;

    /// <summary>Contains: whether the receiver is a string (substring wording + hints).</summary>
    public bool StringInstance;

    /// <summary>SequenceEqual: compiled comparer argument, if present.</summary>
    public string? ComparerSource;
  }

  /// <summary>An [AssertionWrapper] method pair (see AssertionWrapperAttribute in Assertive).</summary>
  internal sealed class WrapperModel
  {
    public string MethodName = "";
    public string ContainingTypeFqn = "";
    public bool IsStatic;
    public string ReturnTypeFqn = "void";
    public List<string> ExtraParameterTypes { get; } = new();
  }
}
