using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace Assertive.Generators
{
  /// <summary>
  /// Intercepts Assert.That / DSL.Assert / [AssertionWrapper] call sites whose lambda body
  /// is a binary ==/!= comparison, replacing delegate evaluation with directly emitted,
  /// typed C#: captured locals are read from the delegate's closure, each operand is
  /// evaluated exactly once, and failures are reported through
  /// GeneratedAssert.EqualityFailure with captured values (EqualsPattern parity).
  ///
  /// There is no expression-tree fallback: call sites outside the whitelist run the plain
  /// delegate and report from source text only, until their patterns are ported.
  /// </summary>
  [Generator]
  public sealed class EqualsInterceptorGenerator : IIncrementalGenerator
  {
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
      var calls = context.SyntaxProvider.CreateSyntaxProvider(
          // Cheap syntax pre-filter: any invocation whose first argument is a zero-parameter
          // lambda literal. The transform's symbol checks reject everything else.
          predicate: static (node, _) => node is InvocationExpressionSyntax invocation
            && invocation.ArgumentList.Arguments.Count > 0
            && invocation.ArgumentList.Arguments[0].Expression is ParenthesizedLambdaExpressionSyntax { ParameterList.Parameters.Count: 0 },
          transform: static (ctx, ct) => CallSiteAnalyzer.Analyze(ctx, ct))
        .Where(static c => c is not null);

      context.RegisterSourceOutput(calls.Collect(), static (spc, all) => Emit(spc, all!));
    }

    private static void Emit(SourceProductionContext spc, ImmutableArray<InterceptedCall?> calls)
    {
      foreach (var fileGroup in calls.Where(c => c != null).GroupBy(c => c!.FilePath))
      {
        // Readable, collision-free: source file stem + stable hash of the full path.
        var stem = new string(System.IO.Path.GetFileNameWithoutExtension(fileGroup.Key)
          .Where(char.IsLetterOrDigit).ToArray());
        var classSuffix = $"{stem}_{StableHash(fileGroup.Key)}";
        var sb = new StringBuilder();

        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable disable");
        sb.AppendLine("#pragma warning disable");
        sb.AppendLine();
        // Short aliases keep the emitted bodies compact. The double-underscore prefix
        // avoids colliding with user identifiers pasted into operand source, matching
        // the convention of the generated locals (__f, __v1, ...). Operand
        // compilation in CallSiteAnalyzer/ExceptionStepCollector emits these same names.
        sb.AppendLine("using __A = global::Assertive.Runtime.GeneratedAssert;");
        sb.AppendLine("using __CP = global::Assertive.Runtime.CustomPatternProbe;");
        sb.AppendLine("using __ES = global::Assertive.Runtime.ExceptionStep;");
        sb.AppendLine("using __ESK = global::Assertive.Runtime.ExceptionStepKind;");
        sb.AppendLine("using __FB = global::System.Func<bool>;");
        sb.AppendLine("using __FC = global::System.Func<object>;");
        sb.AppendLine("using __FE = global::System.Func<global::System.Exception, bool>;");
        sb.AppendLine("using __FO = global::System.Func<object, int, object>;");
        sb.AppendLine("using __FR = global::System.Func<object, int, global::System.Exception>;");
        sb.AppendLine("using __IL = global::System.Runtime.CompilerServices.InterceptsLocationAttribute;");
        sb.AppendLine("using __STH = global::System.Diagnostics.StackTraceHiddenAttribute;");
        sb.AppendLine();
        sb.AppendLine("namespace System.Runtime.CompilerServices");
        sb.AppendLine("{");
        sb.AppendLine("  [global::System.AttributeUsage(global::System.AttributeTargets.Method, AllowMultiple = true)]");
        sb.AppendLine("  file sealed class InterceptsLocationAttribute : global::System.Attribute");
        sb.AppendLine("  {");
        sb.AppendLine("    public InterceptsLocationAttribute(int version, string data)");
        sb.AppendLine("    {");
        sb.AppendLine("      _ = version;");
        sb.AppendLine("      _ = data;");
        sb.AppendLine("    }");
        sb.AppendLine("  }");
        sb.AppendLine("}");
        sb.AppendLine();
        sb.AppendLine("namespace Assertive.Generated");
        sb.AppendLine("{");
        sb.AppendLine("  [__STH]");
        sb.AppendLine($"  internal static class AssertThatInterceptors_{classSuffix}");
        sb.AppendLine("  {");

        // Call sites with identical bodies (same statement text, types and captures) share
        // one interceptor method carrying an [InterceptsLocation] attribute per call site —
        // repeated assertion shapes are common, and the attribute is the only per-site cost.
        var methods = new List<(string Body, string Name, List<InterceptedCall> Calls)>();
        var byBody = new Dictionary<string, int>();
        var index = 0;

        foreach (var call in fileGroup)
        {
          string body;
          string prefix;

          if (call!.Wrapper != null)
          {
            body = BuildWrapperInterceptor(call);
            prefix = "W";
          }
          else if (call.Kind == InterceptionKind.ThrowsPredicate)
          {
            body = BuildThrowsInterceptor(call);
            prefix = "X";
          }
          else
          {
            body = BuildThatInterceptor(call);
            prefix = "T";
          }

          if (byBody.TryGetValue(body, out var existing))
          {
            methods[existing].Calls.Add(call);
          }
          else
          {
            byBody.Add(body, methods.Count);
            methods.Add((body, $"{prefix}{index++}", new List<InterceptedCall> { call }));
          }
        }

        foreach (var (body, name, sites) in methods)
        {
          foreach (var site in sites)
          {
            sb.AppendLine($"    // {System.IO.Path.GetFileName(site.DisplayLocation)}");
            sb.AppendLine($"    [__IL({site.LocationVersion}, {Quote(site.LocationData)})]");
          }

          var nameSlot = body.IndexOf(NamePlaceholder, System.StringComparison.Ordinal);
          sb.Append(body, 0, nameSlot).Append(name).Append(body, nameSlot + NamePlaceholder.Length, body.Length - nameSlot - NamePlaceholder.Length);
          sb.AppendLine();
        }

        sb.AppendLine("  }");
        sb.AppendLine("}");

        spc.AddSource($"AssertThatInterceptors_{classSuffix}.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
      }
    }

    private const string NamePlaceholder = "__NAME__";

    private static string BuildThatInterceptor(InterceptedCall call)
    {
      var parameters = call.Overload switch
      {
        ThatOverload.Context => "__FB __f, __FC __c, string __s, string __cs",
        _ => "__FB __f, object __m, __FC __c, string __s, string __cs",
      };

      var messageArg = call.Overload is ThatOverload.MessageContext ? "__m" : "null";
      var tailArgs = $"{messageArg}, __c, __cs";

      var sb = new StringBuilder();

      sb.AppendLine($"    public static void {NamePlaceholder}({parameters})");
      sb.AppendLine("    {");
      sb.AppendLine($"      __A.Execute(__f, __s, {tailArgs}, __e =>");
      sb.AppendLine("      {");
      BuildRender(sb, call, "__s", tailArgs, "        ");
      sb.AppendLine("      });");
      sb.AppendLine("    }");

      return sb.ToString();
    }

    /// <summary>
    /// Emits an interceptor for an [AssertionWrapper] call site: routes to the wrapper's
    /// AssertionHandle overload carrying a generated assertion action. Instance wrappers
    /// are intercepted with an extension method (receiver as first parameter).
    /// </summary>
    private static string BuildWrapperInterceptor(InterceptedCall call)
    {
      var wrapper = call.Wrapper!;

      var parameters = new List<string>();

      if (!wrapper.IsStatic)
      {
        parameters.Add($"this {wrapper.ContainingTypeFqn} __r");
      }

      parameters.Add("__FB __f");

      for (var i = 0; i < wrapper.ExtraParameterTypes.Count; i++)
      {
        parameters.Add($"{wrapper.ExtraParameterTypes[i]} __p{i}");
      }

      var forwardedArgs = string.Concat(Enumerable.Range(0, wrapper.ExtraParameterTypes.Count).Select(i => $", __p{i}"));
      var target = wrapper.IsStatic ? wrapper.ContainingTypeFqn : "__r";
      var returnKeyword = wrapper.ReturnTypeFqn == "void" ? "" : "return ";

      var sb = new StringBuilder();

      sb.AppendLine($"    public static {wrapper.ReturnTypeFqn} {NamePlaceholder}({string.Join(", ", parameters)})");
      sb.AppendLine("    {");
      // A local const: referenced from both lambdas without forcing a capture.
      sb.AppendLine($"      const string __s = {Quote(call.BodySource)};");
      sb.AppendLine($"      {returnKeyword}{target}.{wrapper.MethodName}(global::Assertive.AssertionHandle.Generated([__STH] () =>");
      sb.AppendLine("        __A.Execute(__f, __s, null, null, null, __e =>");
      sb.AppendLine("        {");
      BuildRender(sb, call, "__s", "null, null, null", "          ");
      sb.AppendLine($"        }})){forwardedArgs});");
      sb.AppendLine("    }");

      return sb.ToString();
    }

    /// <summary>
    /// Emits an interceptor for an Assert.Throws call with an exception-predicate lambda.
    /// Behavior is delegated to the runtime (GeneratedAssert.ThrowsIntercepted); the
    /// interceptor contributes a factory that decomposes the classified predicate body
    /// with the thrown exception bound to its parameter. The predicate parameter is named
    /// __f because compiled operands read captured locals from that delegate.
    /// </summary>
    private static string BuildThrowsInterceptor(InterceptedCall call)
    {
      var exceptionType = call.ThrowsExceptionTypeFqn ?? "global::System.Exception";

      var actionType = call.ThrowsActionKind switch
      {
        ThrowsActionKind.Action => "global::System.Action",
        ThrowsActionKind.FuncObject => "__FC",
        _ => "global::System.Func<global::System.Threading.Tasks.Task>",
      };

      var isAsync = call.ThrowsActionKind == ThrowsActionKind.FuncTask;
      var returnType = isAsync ? $"global::System.Threading.Tasks.Task<{exceptionType}>" : exceptionType;

      var actionArg = call.ThrowsActionKind == ThrowsActionKind.FuncObject
        ? "new global::System.Action(() => { _ = __d(); })"
        : "__d";

      var expectedTypeArg = call.ThrowsExceptionTypeFqn != null ? $"typeof({call.ThrowsExceptionTypeFqn})" : "null";
      var runtimeEntry = isAsync ? "ThrowsInterceptedAsync" : "ThrowsIntercepted";
      var awaitKeyword = isAsync ? "await " : "";

      var sb = new StringBuilder();

      sb.AppendLine($"    public static {(isAsync ? "async " : "")}{returnType} {NamePlaceholder}({actionType} __d, global::System.Func<{exceptionType}, bool> __f, string __ds, string __xs)");
      sb.AppendLine("    {");
      sb.AppendLine($"      return ({exceptionType}){awaitKeyword}__A.{runtimeEntry}(");
      sb.AppendLine($"        {actionArg},");
      sb.AppendLine($"        {expectedTypeArg},");
      sb.AppendLine($"        __f == null ? null : new __FE(__e => __f(({exceptionType})__e)),");
      sb.AppendLine("        __ds, __xs,");
      sb.AppendLine($"        {BuildSubRenderer(call.AllSubCall, Quote(call.BodySource), "        ", call)});");
      sb.AppendLine("    }");

      return sb.ToString();
    }

    private static void EmitCaptureDecls(StringBuilder sb, InterceptedCall call, string delegateName, string indent)
    {
      foreach (var local in call.CapturedLocals)
      {
        var name = CallSiteAnalyzer.Identifier(local.Name);

        // Unnameable types are read as object; member access on them happens reflectively.
        sb.AppendLine(local.Type != null
          ? $"{indent}{local.Type} {name} = ({local.Type})__A.GetCapturedValue({delegateName}, {Quote(local.Name)});"
          : $"{indent}object {name} = __A.GetCapturedValue({delegateName}, {Quote(local.Name)});");
      }
    }

    /// <summary>
    /// Locals that are themselves a whole operand are already displayed as the operand
    /// value; everything else captured shows up under LOCALS (mirrors LocalsProvider).
    /// </summary>
    private static string BuildLocalsArray(InterceptedCall call)
      => BuildLocalsArray(call.CapturedLocals, call.LeftDisplay, call.RightDisplay);

    private static string BuildLocalsArray(IEnumerable<(string Name, string? Type)> locals, string leftDisplay, string rightDisplay)
    {
      // Display sources keep verbatim identifiers as written (@lock), symbol names don't.
      var displayedLocals = locals
        .Where(l => l.Name != leftDisplay.Trim().TrimStart('@') && l.Name != rightDisplay.Trim().TrimStart('@'))
        .ToList();

      return displayedLocals.Count == 0
        ? "[]"
        : $"[{string.Join(", ", displayedLocals.Select(l => $"({Quote(l.Name)}, (object){CallSiteAnalyzer.Identifier(l.Name)})"))}]";
    }

    /// <summary>
    /// Emits the shared evaluation core. The original delegate decides pass/fail — exactly
    /// one evaluation, no generated comparison semantics. Only on failure are the operands
    /// re-evaluated (typed or reflectively) for the decomposed report, mirroring how the
    /// expression-based pipeline re-evaluated sub-expressions during failure analysis.
    /// </summary>
    /// <summary>
    /// Emits the body of the render callback passed to GeneratedAssert.Execute, which owns
    /// all scaffolding (single delegate evaluation, exception filtering, best-effort
    /// fallbacks). The callback only builds the report: captures and locals once, the
    /// exception case first, then operand re-evaluation and the classified decomposition.
    /// </summary>
    private static void BuildRender(StringBuilder sb, InterceptedCall call, string assertionTextArg, string tailArgs, string indent)
    {
      EmitCaptureDecls(sb, call, "__f", indent);

      sb.AppendLine($"{indent}(string, object)[] __l = {BuildLocalsArray(call)};");

      var steps = call.ExceptionStepsSource ?? "null";

      sb.AppendLine($"{indent}if (__e != null)");
      sb.AppendLine($"{indent}{{");
      sb.AppendLine($"{indent}  return __A.EvaluationFailure({assertionTextArg}, __e, {steps}, __l, {tailArgs});");
      sb.AppendLine($"{indent}}}");

      // The Bool/Opaque/Split patterns need no operand values (the delegate already
      // evaluated the body); everything else re-evaluates the operand(s) it reports on.
      if (call.Kind is not (InterceptionKind.Bool or InterceptionKind.Opaque or InterceptionKind.Split))
      {
        sb.AppendLine($"{indent}var __v1 = {call.LeftSource};");
      }

      if (HasRightOperand(call.Kind))
      {
        sb.AppendLine($"{indent}var __v2 = {call.RightSource};");
      }

      var tail = $"__l, {tailArgs}";

      // Runtime-registered custom patterns take precedence over the built-in decomposition
      // (the old FallbackPattern consulted them first).
      if (call.CustomProbeSource != null)
      {
        sb.AppendLine($"{indent}if (__A.TryCustomFailure({assertionTextArg},");
        sb.AppendLine($"{indent}  {call.CustomProbeSource},");
        sb.AppendLine($"{indent}  {tail}) is {{ }} __u)");
        sb.AppendLine($"{indent}{{");
        sb.AppendLine($"{indent}  return __u;");
        sb.AppendLine($"{indent}}}");
      }

      if (call.Kind == InterceptionKind.Split)
      {
        var leaves = FlattenLeaves(call.SplitRoot!);

        if (IsPureAndAlso(call.SplitRoot!))
        {
          BuildAndChain(sb, leaves, assertionTextArg, tailArgs, indent);
        }
        else
        {
          BuildFlagsChain(sb, leaves, assertionTextArg, tailArgs, indent);
        }

        return;
      }

      sb.AppendLine($"{indent}return __A.{BuildFailureInvocation(call, assertionTextArg, indent, tail, "__v1", "__v2")});");
    }

    /// <summary>The split's leaves in evaluation order; the operator structure is not kept.</summary>
    private static List<SplitPart> FlattenLeaves(SplitPart part)
    {
      var leaves = new List<SplitPart>();

      Collect(part, leaves);

      return leaves;

      static void Collect(SplitPart part, List<SplitPart> leaves)
      {
        if (part.Kind == "Leaf")
        {
          leaves.Add(part);
          return;
        }

        Collect(part.Left!, leaves);
        Collect(part.Right!, leaves);
      }
    }

    private static bool IsPureAndAlso(SplitPart part)
      => part.Kind == "Leaf" || (part.Kind == "AndAlso" && IsPureAndAlso(part.Left!) && IsPureAndAlso(part.Right!));

    /// <summary>
    /// The compact split form for &amp;&amp;-only bodies: re-evaluate the conjuncts in order with
    /// short-circuit semantics, recording the index of the one that failed (or threw), then
    /// render that leaf's classified report in a switch. &amp;&amp; short-circuits, so exactly one
    /// conjunct can fail — no part tree needed.
    /// </summary>
    private static void BuildAndChain(StringBuilder sb, List<SplitPart> leaves, string assertionTextArg, string tailArgs, string indent)
    {
      sb.AppendLine($"{indent}var __k = 0;");
      sb.AppendLine($"{indent}var __ok = false;");
      sb.AppendLine($"{indent}global::System.Exception __le = null;");
      sb.AppendLine($"{indent}try");
      sb.AppendLine($"{indent}{{");
      sb.AppendLine($"{indent}  __ok = (bool)(object)({leaves[0].ConditionSource});");

      for (var i = 1; i < leaves.Count; i++)
      {
        sb.AppendLine($"{indent}  if (__ok) {{ __k = {i}; __ok = (bool)(object)({leaves[i].ConditionSource}); }}");
      }

      sb.AppendLine($"{indent}}}");
      sb.AppendLine($"{indent}catch (global::System.Exception __t) when (!__A.IsAssertionFailure(__t))");
      sb.AppendLine($"{indent}{{");
      sb.AppendLine($"{indent}  __le = __t;");
      sb.AppendLine($"{indent}}}");
      sb.AppendLine($"{indent}if (__ok)");
      sb.AppendLine($"{indent}{{");
      sb.AppendLine($"{indent}  // The delegate said false but re-evaluation disagrees (non-deterministic input).");
      sb.AppendLine($"{indent}  return __A.Failure({assertionTextArg}, null, {tailArgs});");
      sb.AppendLine($"{indent}}}");
      sb.AppendLine($"{indent}switch (__k)");
      sb.AppendLine($"{indent}{{");

      for (var i = 0; i < leaves.Count; i++)
      {
        sb.AppendLine($"{indent}  {(i == leaves.Count - 1 ? "default:" : $"case {i}:")}");
        sb.AppendLine($"{indent}  {{");
        EmitLeafCase(sb, leaves[i], tailArgs, indent + "    ");
        sb.AppendLine($"{indent}  }}");
      }

      sb.AppendLine($"{indent}}}");
    }

    /// <summary>One conjunct's report: leaf-scoped locals once, the exception case, then the classified decomposition.</summary>
    private static void EmitLeafCase(StringBuilder sb, SplitPart part, string tailArgs, string indent)
    {
      var leafText = Quote(part.LeafSource);
      var localsArray = BuildLocalsArray(part.Locals, part.SubCall?.LeftDisplay ?? "", part.SubCall?.RightDisplay ?? "");

      sb.AppendLine($"{indent}(string, object)[] __l2 = {localsArray};");
      sb.AppendLine($"{indent}if (__le != null)");
      sb.AppendLine($"{indent}{{");
      sb.AppendLine($"{indent}  return __A.EvaluationFailure({leafText}, __le, {part.StepsSource ?? "null"}, __l2, {tailArgs});");
      sb.AppendLine($"{indent}}}");

      EmitLeafOperands(sb, part, indent);

      sb.AppendLine($"{indent}return {LeafReport(part, leafText, $"__l2, {tailArgs}", indent)};");
    }

    /// <summary>
    /// The split form for bodies with &amp;, | or ||: every leaf is re-evaluated in order and
    /// the failing ones are recorded as bits, so multiple leaves can report (the operator
    /// structure itself is not replayed). A leaf that throws stops the chain and its
    /// report carries the exception.
    /// </summary>
    private static void BuildFlagsChain(StringBuilder sb, List<SplitPart> leaves, string assertionTextArg, string tailArgs, string indent)
    {
      if (leaves.Count > 31)
      {
        // Doesn't fit the flags integer; nobody composes 32 leaves, but degrade to source text.
        sb.AppendLine($"{indent}return __A.Failure({assertionTextArg}, __l, {tailArgs});");
        return;
      }

      sb.AppendLine($"{indent}var __k = 0;");
      sb.AppendLine($"{indent}var __n = 0;");
      sb.AppendLine($"{indent}global::System.Exception __le = null;");
      sb.AppendLine($"{indent}try");
      sb.AppendLine($"{indent}{{");

      for (var i = 0; i < leaves.Count; i++)
      {
        var track = i == 0 ? "" : $"__n = {i}; ";
        sb.AppendLine($"{indent}  {track}if (!(bool)(object)({leaves[i].ConditionSource})) __k |= {1 << i};");
      }

      sb.AppendLine($"{indent}}}");
      sb.AppendLine($"{indent}catch (global::System.Exception __t) when (!__A.IsAssertionFailure(__t))");
      sb.AppendLine($"{indent}{{");
      sb.AppendLine($"{indent}  __le = __t;");
      sb.AppendLine($"{indent}  __k |= 1 << __n;");
      sb.AppendLine($"{indent}}}");
      sb.AppendLine($"{indent}if (__k == 0)");
      sb.AppendLine($"{indent}{{");
      sb.AppendLine($"{indent}  // The delegate said false but re-evaluation disagrees (non-deterministic input).");
      sb.AppendLine($"{indent}  return __A.Failure({assertionTextArg}, null, {tailArgs});");
      sb.AppendLine($"{indent}}}");
      sb.AppendLine($"{indent}var __fs = new global::System.Collections.Generic.List<global::System.Exception>();");

      for (var i = 0; i < leaves.Count; i++)
      {
        EmitLeafFlag(sb, leaves[i], i, tailArgs, indent);
      }

      sb.AppendLine($"{indent}return __A.CombinedFailure(__fs);");
    }

    private static void EmitLeafFlag(StringBuilder sb, SplitPart part, int index, string tailArgs, string indent)
    {
      var inner = indent + "  ";
      var leafText = Quote(part.LeafSource);
      var localsArray = BuildLocalsArray(part.Locals, part.SubCall?.LeftDisplay ?? "", part.SubCall?.RightDisplay ?? "");

      sb.AppendLine($"{indent}if ((__k & {1 << index}) != 0)");
      sb.AppendLine($"{indent}{{");
      sb.AppendLine($"{inner}(string, object)[] __l2 = {localsArray};");
      sb.AppendLine($"{inner}if (__le != null && __n == {index})");
      sb.AppendLine($"{inner}{{");
      sb.AppendLine($"{inner}  __fs.Add(__A.EvaluationFailure({leafText}, __le, {part.StepsSource ?? "null"}, __l2, {tailArgs}));");
      sb.AppendLine($"{inner}}}");
      sb.AppendLine($"{inner}else");
      sb.AppendLine($"{inner}{{");
      EmitLeafOperands(sb, part, inner + "  ");
      sb.AppendLine($"{inner}  __fs.Add({LeafReport(part, leafText, $"__l2, {tailArgs}", inner + "  ")});");
      sb.AppendLine($"{inner}}}");
      sb.AppendLine($"{indent}}}");
    }

    private static void EmitLeafOperands(StringBuilder sb, SplitPart part, string indent)
    {
      if (part.SubCall is not { } sub)
      {
        return;
      }

      if (sub.Kind is not (InterceptionKind.Bool or InterceptionKind.Opaque))
      {
        sb.AppendLine($"{indent}var __y1 = {sub.LeftSource};");
      }

      if (HasRightOperand(sub.Kind))
      {
        sb.AppendLine($"{indent}var __y2 = {sub.RightSource};");
      }
    }

    /// <summary>The leaf's classified decomposition, custom patterns first.</summary>
    private static string LeafReport(SplitPart part, string leafText, string leafTail, string indent)
    {
      var probe = part.ProbeSource != null
        ? $"__A.TryCustomFailure({leafText}, {part.ProbeSource}, {leafTail}) ?? "
        : "";

      return part.SubCall is { } sub
        ? $"{probe}__A.{BuildFailureInvocation(sub, leafText, indent, leafTail, "__y1", "__y2")})"
        : $"{probe}__A.Failure({leafText}, {leafTail})";
    }

    private static bool HasRightOperand(InterceptionKind kind)
      => kind is InterceptionKind.Equality or InterceptionKind.ReferenceEquals
        or InterceptionKind.Comparison or InterceptionKind.Length
        or InterceptionKind.Contains or InterceptionKind.StartsEndsWith or InterceptionKind.SequenceEqual;

    /// <summary>
    /// The GeneratedAssert.XFailure(...) invocation for a classified call, parameterized on
    /// the operand local names so it serves both the top-level throw and the per-item
    /// sub-failure renderers of the All pattern.
    /// </summary>
    private static string BuildFailureInvocation(InterceptedCall call, string assertionTextArg, string indent, string tail, string left, string right)
    {
      var negated = call.Negated ? "true" : "false";
      var rightIsConstant = call.RightIsConstant ? "true" : "false";

      return call.Kind switch
      {
        InterceptionKind.Equality =>
          $"EqualityFailure(\n{indent}  {assertionTextArg},\n{indent}  {Quote(call.LeftDisplay)}, (object){left},\n{indent}  {Quote(call.RightDisplay)}, (object){right},\n{indent}  {rightIsConstant}, {negated},\n{indent}  {tail}",
        InterceptionKind.ReferenceEquals =>
          $"ReferenceEqualsFailure(\n{indent}  {assertionTextArg},\n{indent}  {Quote(call.LeftDisplay)}, (object){left},\n{indent}  {Quote(call.RightDisplay)}, (object){right},\n{indent}  {negated},\n{indent}  {tail}",
        InterceptionKind.Bool =>
          $"BoolFailure(\n{indent}  {assertionTextArg},\n{indent}  {Quote(call.LeftDisplay)}, {negated},\n{indent}  {tail}",
        InterceptionKind.Null =>
          $"NullFailure(\n{indent}  {assertionTextArg},\n{indent}  {Quote(call.LeftDisplay)}, (object){left}, {negated},\n{indent}  {tail}",
        InterceptionKind.HasValue =>
          $"HasValueFailure(\n{indent}  {assertionTextArg},\n{indent}  {Quote(call.LeftDisplay)}, (object){left}, {negated},\n{indent}  {tail}",
        InterceptionKind.Is =>
          $"IsTypeFailure(\n{indent}  {assertionTextArg},\n{indent}  {Quote(call.LeftDisplay)}, (object){left}, {call.TypeAccessor}, {negated},\n{indent}  {tail}",
        InterceptionKind.Comparison =>
          $"ComparisonFailure(\n{indent}  {assertionTextArg},\n{indent}  {Quote(call.LeftDisplay)}, (object){left},\n{indent}  {Quote(call.RightDisplay)}, (object){right},\n{indent}  {rightIsConstant}, {Quote(call.ComparisonLabel ?? "")},\n{indent}  {tail}",
        InterceptionKind.Length =>
          $"LengthFailure(\n{indent}  {assertionTextArg},\n{indent}  {Quote(call.OperandDisplay)}, {(call.FilterSource != null ? Quote(call.FilterSource) : "null")}, {Quote(call.CountLabel)}, {Quote(call.ComparisonLabel ?? "")},\n{indent}  (object){left},\n{indent}  {Quote(call.RightDisplay)}, (object){right}, {rightIsConstant},\n{indent}  {tail}",
        InterceptionKind.Contains =>
          $"ContainsFailure(\n{indent}  {assertionTextArg},\n{indent}  {Quote(call.LeftDisplay)}, (object){left},\n{indent}  {Quote(call.RightDisplay)}, (object){right},\n{indent}  {rightIsConstant}, {(call.StringInstance ? "true" : "false")}, {negated},\n{indent}  {tail}",
        InterceptionKind.StartsEndsWith =>
          $"StartsEndsWithFailure(\n{indent}  {assertionTextArg},\n{indent}  {Quote(call.LeftDisplay)}, (object){left},\n{indent}  {Quote(call.RightDisplay)}, (object){right},\n{indent}  {rightIsConstant}, {Quote(call.ComparisonLabel ?? "")}, {negated},\n{indent}  {tail}",
        InterceptionKind.Any =>
          $"AnyFailure(\n{indent}  {assertionTextArg},\n{indent}  {Quote(call.OperandDisplay)}, {(call.FilterSource != null ? Quote(call.FilterSource) : "null")}, {negated}, {left},\n{indent}  {tail}",
        InterceptionKind.SequenceEqual =>
          $"SequenceEqualFailure(\n{indent}  {assertionTextArg},\n{indent}  {Quote(call.LeftDisplay)}, (object){left},\n{indent}  {Quote(call.RightDisplay)}, (object){right},\n{indent}  {(call.ComparerSource != null ? $"(object)({call.ComparerSource})" : "null")}, {call.TypeAccessor ?? "null"},\n{indent}  {tail}",
        InterceptionKind.All =>
          $"AllFailure(\n{indent}  {assertionTextArg},\n{indent}  {Quote(call.OperandDisplay)}, {Quote(call.FilterSource ?? "")}, {(call.CollectionIsMethodCall ? "true" : "false")}, (object){left}, {negated},\n{indent}  {call.AllFilterFunc ?? "null"},\n{indent}  {BuildSubRenderer(call.AllSubCall, Quote(call.FilterSource ?? ""), indent)},\n{indent}  {tail}",
        InterceptionKind.Opaque =>
          $"Failure(\n{indent}  {assertionTextArg},\n{indent}  {tail}",
        _ => throw new System.InvalidOperationException($"Unhandled kind {call.Kind}"),
      };
    }

    /// <summary>
    /// A bound sub-failure factory: evaluates the classified sub-assertion's operands with
    /// the bound value (an All item, or the exception caught by Throws) and builds the
    /// corresponding failure exception. Its expected/actual data becomes the sub-message.
    /// </summary>
    private static string BuildSubRenderer(InterceptedCall? sub, string assertionTextArg, string indent, InterceptedCall? captureFrom = null)
    {
      if (sub == null)
      {
        return "null";
      }

      var inner = indent + "    ";
      var renderer = new StringBuilder();

      renderer.Append("(__FR)((__i, __j) =>\n");
      renderer.Append($"{indent}  {{\n");

      // The Throws interceptor declares its captures here rather than in the method body:
      // the renderer only runs on the (already guarded) failure path, so a reflective
      // capture failure can't break the passing path. All-pattern renderers instead use
      // the captures already declared in the enclosing reporting scope.
      if (captureFrom != null)
      {
        EmitCaptureDecls(renderer, captureFrom, "__f", inner);
      }

      if (sub.Kind is not (InterceptionKind.Bool or InterceptionKind.Opaque))
      {
        renderer.Append($"{inner}var __w1 = {sub.LeftSource};\n");
      }

      if (HasRightOperand(sub.Kind))
      {
        renderer.Append($"{inner}var __w2 = {sub.RightSource};\n");
      }

      var subTail = $"[],\n{inner}  null, null, null";

      renderer.Append($"{inner}return __A.{BuildFailureInvocation(sub, assertionTextArg, inner, subTail, "__w1", "__w2")});\n");
      renderer.Append($"{indent}  }})");

      return renderer.ToString();
    }

    private static string Quote(string text) => SymbolDisplay.FormatLiteral(text, quote: true);

    private static string StableHash(string text)
    {
      // FNV-1a; string.GetHashCode is not stable across runs on modern runtimes.
      unchecked
      {
        var hash = 2166136261u;

        foreach (var c in text)
        {
          hash = (hash ^ c) * 16777619u;
        }

        return hash.ToString("x8");
      }
    }
  }

  internal enum ThatOverload
  {
    Context,
    MessageContext,
  }

  /// <summary>The shape of an intercepted Assert.Throws first parameter.</summary>
  internal enum ThrowsActionKind
  {
    Action,
    FuncObject,
    FuncTask,
  }

  internal enum InterceptionKind
  {
    Equality,
    ReferenceEquals,
    Bool,
    Null,
    HasValue,
    Is,
    Comparison,
    Length,
    Contains,
    StartsEndsWith,
    Any,
    SequenceEqual,
    All,

    /// <summary>
    /// An Assert.Throws call with an exception-predicate lambda; the predicate body is
    /// classified as a sub-assertion bound to the thrown exception.
    /// </summary>
    ThrowsPredicate,

    /// <summary>
    /// A logically-composed body (`a &amp;&amp; b`, `a &amp; b`, ...): split into leaf assertions
    /// that report individually with operator semantics.
    /// </summary>
    Split,

    /// <summary>
    /// Not a decomposable form: the false path reports source text + locals only, but the
    /// call is still intercepted so the exception path gets cause attribution.
    /// </summary>
    Opaque,
  }

  internal sealed class InterceptedCall
  {
    public int LocationVersion;
    public string LocationData = "";
    public string DisplayLocation = "";
    public string FilePath = "";
    public ThatOverload Overload;
    public WrapperModel? Wrapper;
    public InterceptionKind Kind;

    /// <summary>Captured locals to declare; Type is null for unnameable types (read as object).</summary>
    public List<(string Name, string? Type)> CapturedLocals { get; } = new();

    public string BodySource = "";
    public string LeftSource = "";
    public string RightSource = "";
    public string LeftDisplay = "";
    public string RightDisplay = "";

    /// <summary>
    /// Message-level negation. Per kind: Equality reads "should not equal", Null means
    /// "expected null", Bool/HasValue/Is/ReferenceEquals negate their message.
    /// </summary>
    public bool Negated;
    public bool RightIsConstant;

    /// <summary>Comparison/Length: "less than", "equal to", ...</summary>
    public string? ComparisonLabel;

    /// <summary>Length: "Length" or "Count".</summary>
    public string CountLabel = "";

    /// <summary>Length: the collection/string operand (receiver of the Length/Count access).</summary>
    public string OperandDisplay = "";

    /// <summary>Length: source of the Count(...) filter lambda body, if any.</summary>
    public string? FilterSource;

    /// <summary>Is: C# expression evaluating to the checked System.Type. SequenceEqual: the element type.</summary>
    public string? TypeAccessor;

    /// <summary>Contains: whether the receiver is a string (substring wording + hints).</summary>
    public bool StringInstance;

    /// <summary>SequenceEqual: compiled comparer argument, if present.</summary>
    public string? ComparerSource;

    /// <summary>All: whether the collection operand is itself a method call (changes the per-item prefix).</summary>
    public bool CollectionIsMethodCall;

    /// <summary>All: compiled `(item, index) => bool` filter used to find the failing items.</summary>
    public string? AllFilterFunc;

    /// <summary>All: the filter body classified as a per-item sub-assertion, if decomposable.</summary>
    public InterceptedCall? AllSubCall;

    /// <summary>
    /// `new ExceptionStep[] { ... }` source for exception-cause attribution on the
    /// failure path, or null when the body has no throw-capable sub-expressions.
    /// </summary>
    public string? ExceptionStepsSource;

    /// <summary>
    /// `new CustomPatternProbe { ... }` source for runtime custom-pattern matching, or
    /// null when the body root is not a method call / property access.
    /// </summary>
    public string? CustomProbeSource;

    /// <summary>ThrowsPredicate: the shape of the intercepted Throws action parameter.</summary>
    public ThrowsActionKind ThrowsActionKind;

    /// <summary>ThrowsPredicate: the expected exception type, or null for the non-generic overloads.</summary>
    public string? ThrowsExceptionTypeFqn;

    /// <summary>Split: the part tree of a logically-composed body.</summary>
    public SplitPart? SplitRoot;
  }

  /// <summary>
  /// Generator-side node of a logically-composed assertion body; emitted as an
  /// Assertive.Runtime.AssertionPart tree.
  /// </summary>
  internal sealed class SplitPart
  {
    /// <summary>AssertionPartKind member name: Leaf, AndAlso, And, OrElse, Or.</summary>
    public string Kind = "Leaf";

    public SplitPart? Left;
    public SplitPart? Right;

    public string LeafSource = "";

    /// <summary>Compiled re-evaluation of the leaf.</summary>
    public string? ConditionSource;

    /// <summary>The leaf classified as its own assertion, or null (source-text report).</summary>
    public InterceptedCall? SubCall;

    /// <summary>Exception steps scoped to this leaf, for re-evaluation throws.</summary>
    public string? StepsSource;

    /// <summary>Custom-pattern probe for the leaf root, if it is a call/property.</summary>
    public string? ProbeSource;

    /// <summary>Captured locals introduced by this leaf's compilations.</summary>
    public List<(string Name, string? Type)> Locals { get; } = new();
  }

  /// <summary>An [AssertionWrapper] method pair (see AssertionWrapperAttribute in Assertive).</summary>
  internal sealed class WrapperModel
  {
    public string MethodName = "";
    public string ContainingTypeFqn = "";
    public bool IsStatic;
    public string ReturnTypeFqn = "void";
    public List<string> ExtraParameterTypes { get; } = new();
  }
}
